name: github pages deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build
      - run: git config user.name "GitHub Actions" && git config user.email "actions@users.noreply.github.com"
      - run: git fetch
      - run: git checkout gh-pages
      - run: find . -not -path './dist*' -not -path './.git*' -not -path './README*' -not -path './LICENSE*' -delete
      - run: rm -rf dist/
      - run: mv dist/* .
      - run: git add -A
      - run: git status
      - run: git commit -m 'Github Actions Deploy'
      - run: git push origin gh-pages
